### ISSUE TITLE
Payment History Visualization 

### ISSUE THREAD

**Issue by Ly0n** [protontypes/openselery#12]
Create a Payment History Plot with Jupiter Notebook

**Comment by Ly0n** [comment]
By converting Jupyter Notebooks to rst a visualization in Github Wiki is possible

**Comment by Ly0n** [comment]
What we want to plot:
Total Payout over Months --> Bar Chart 
Total Payout over Day --> Bar Chart
Transactions per User --> Bar Chart
1. As artifacts png
2. Pushed to Wiki

**Comment by cornerman** [comment]
Fixed with 4e4e98bc22d1ff5e2391a5d3896df7b18d37c08d
