### ISSUE TITLE
Visualization of dependency tree from the target repository 

### ISSUE THREAD

**Issue by Ly0n** [protontypes/openselery#13]
A nice side effect of OpenSelery could be the visualization of the project dependency tree. All the data should already be there.
The data we can put into the wiki of the project.
Here an example how that would look like for Python:
https://github.com/thebjorn/pydeps

**Comment by krux02** [comment]
Since I wast to work on this, can you explain me again, where in OpenSelery I can find the dependency tree? Also an example project with an interesting dependency tree would be nice.

**Comment by Ly0n** [comment]
Do need to solve this is since Github has already integrated this now in a good way:
https://github.com/protontypes/openselery/network/dependencies.
Sorry have not seen that before ^^
