### ISSUE TITLE
We need a minimum threshold for allowed payouts per contributors

### ISSUE THREAD

**Issue by Ly0n** [protontypes/openselery#140]
Problem:
Depending on the configuration we could have a very low payout that could be perceived as spam

Possible Solutions:
Let us skip this payout to avoid spam.

**Comment by domdfcoding** [comment]
I concur. When I received first received the email from Coinbase I thought it was spam until I investigated further.

**Comment by Ly0n** [comment]
> I concur. When I received first received the email from Coinbase I thought it was spam until I investigated further.
We will add this to the public beta release next week.

**Comment by Ly0n** [comment]
@domdfcoding What do you think would be a good lower bound? about 2€?

**Comment by Ly0n** [comment]
Solved by 073e6caa3631c7ec1d2802f52458ddec21d9a5d6

**Comment by krux02** [comment]
I think currently about youtube and twitch. Those platforms don't hold back to send a tiny amount of money to the content creators. I am not sure exactly whey they are doing it this way, but I think it has to do with the very low income you get per view. But also also suggest there are some hidden reasons behind that we don't fully understand. If you ask my personal opinion about a minimum payout threshold, it could be in the area of cents, for example 10¢ would be fine for me.
