### ISSUE TITLE
Push results of transaction visualization to Github Wiki

### ISSUE THREAD

**Issue by Ly0n** [protontypes/openselery#42]
After the transactions are plotted into artifacts we want to push them to the Github Wiki since the artifacts can not be seen by others users. The results should be plotted in a nice way.

**Comment by cornerman** [comment]
Plots are now part of the artifacts (inside result folder).

**Comment by Ly0n** [comment]
The scaling of the transaction history images is now improved so that the images give a good overview. 
I also created a static custom badge with https://badgen.net.

Two points still needs to be solved from my point of view:
1. Anonymization of Email Addresses. 
2. Increase gab between bars in the user over total payout plot. 

For the anonymization I tested the Github API to transform private email addresses into Github user names. It works like in this example:
https://stackoverflow.com/questions/44888187/get-github-username-through-primary-email
The problem is the number of allowed API calls. In this way every contributor creates one API call. 
Maybe we could use contributor object to transform Github Email into username.  
Do you see a better solution? Maybe just just wildcats like this:
tobias.****rger@protontypes.eu

@cornerman @kikass13  @krux02

**Comment by Ly0n** [comment]
Further steps in #82
