### ISSUE TITLE
Use weights to split the total amount instead of random choice

### ISSUE THREAD

**Issue by Ly0n** [protontypes/openselery#44]
The distribution of payout is can be done via Coinbase without any fee between wallets:
> We do not charge for transferring cryptocurrency from one Coinbase wallet to another [[1]](https://help.coinbase.com/en/coinbase/trading-and-funding/pricing-and-fees/fees)

Since no fees are created OpenSelery could use the Coinbase API for micro-transaction. In this way we could avoid the random choice function.

Split or Random choice should be configurable for every contributor type ( Target Project, Dependency contributor and tooling contributor)

# Pro
* OpenSelery does not look like gambling
* OpenSelery is much more deterministic and transparent.

# Con
* This approach does not work with Paypal in this same way with a standard account. Only transactions between "friends" are for free.
* For larger projects the minimum amount to payout should be limited.
* The approach does not work for including dependencies. Here the random choice function could be a solution.

**Comment by cornerman** [comment]
Make this configurable between random and split
