### ISSUE TITLE
Create a pip package

### ISSUE THREAD

**Issue by cornerman** [protontypes/openselery#58]
As soon as ruby dependency is gone

**Comment by kikass13** [comment]
i am gonna do that this week (python-setup lets go)

**Comment by kikass13** [comment]
should be done for now

**Comment by Ly0n** [comment]
Create work @kikass13 
You can now install openselery as a pip package after small changes to the setup.py to conform with PyPi Standards
```
pip install openselery
```
Testing will continue tomorrow.
