### ISSUE TITLE
Create a simple Flow Chart for the README

### ISSUE THREAD

**Issue by Ly0n** [protontypes/openselery#61]
Create a flow chart to make OpenSelery more accessible for people visiting the project.

**Comment by kikass13** [comment]
https://github.com/mpnsk/does-github-support-mermaid

.... -.-

**Comment by kikass13** [comment]
maybe you guys can use this 
https://github.com/BackMarket/github-mermaid-extension

for embedding mermaid.

or switch tu gitlab

**Comment by Ly0n** [comment]
The Gitlab support will be focused in the future when we reached a critical mass of users. For the flow chart I was more thinking of simple one like this:
https://gitfund.io/static/gfx/97bd515e5c6c9c86d9a4a82c5eb228c731ac7f45-gitfund-overview.png

**Comment by kikass13** [comment]
i was just ranting, because mermaid is perfect for stuff like this and github is not including it ...

**Comment by Ly0n** [comment]
I created a very basic "flow chart":
https://github.com/protontypes/openselery/blob/master/docs/selery_workflow.png
For the documentation website we need on that is more detailed and shows the actual architecture.
