### ISSUE TITLE
OpenSelery should only run with a full configured selery.yml

### ISSUE THREAD

**Issue by Ly0n** [protontypes/openselery#93]
Since the configurations of parameters highly interacts with other parameters we should always check if all parameters are set. 
Especially with the Split mode we should not run on default values. Use could create an absolute unwanted behavior if you miss this parameter. Since transparency should be our focus we should give a user an overview over all parameters by the openselery.yml file. @kikass13 @cornerman @krux02 
What is your opinion on the subject?

**Comment by kikass13** [comment]
I am against defaults, 

the cong is all ready printed out onto the terminal

**Comment by Ly0n** [comment]
Yes, me too. When I remove one of the parameters of the selery.yml file the default value of [this line](https://github.com/protontypes/openselery/blob/master/openselery/configuration.py#L24) is been used. We need a isConfigurationComplete function that checks if all parameters are set.

**Comment by kikass13** [comment]
well that's an easy fix,
im gonna do that on sunday or smth :D

**Comment by Ly0n** [comment]
Closed by 3aa02d8300512aceb952f6dc453ef76e9a38b16a

**Comment by Ly0n** [comment]
Unfortunately I still can delete configuration from the selery.yml and OpenSelery still does run without any error or warning. 
I tested that on the VPS.

**Comment by krux02** [comment]
There should be a test case for this.

**Comment by kikass13** [comment]
@Ly0n 
i tested it right now ... 
openselery will throw an 
```AttributeError: OpenseleryConfig has no attribute 'bitcoin_address' ```

what did you do?

**Comment by Ly0n** [comment]
OpenSelery just fails when the parameter is actually been used. When I remove "skip_email" in simulation mode OpenSelery runs like a charm because this is only been used in payout. That's why I was thinking it does not work. My expectation was that every possible parameter will be check for existence when loaded. Maybe this is also not the behavior that you want. In the future you don't want to set every paramter because maybe you have just a limited amount of parameter that are been used based on your split mode. @cornerman @krux02   What do you think?

**Comment by cornerman** [comment]
I agree that parameters should be checked in the beginning with proper error messages. Otherwise the program just crashes in the middle of the execution without proper explanation. And during the failed run, some steps might have succeeded.

**Comment by kikass13** [comment]
well i do agree that this is useful, but that was not something argued in the pull request.
I can do that and provide another merge

**Comment by Ly0n** [comment]
Nice @kikass13

**Comment by Ly0n** [comment]
Solved by #115
